# Generated by Django 5.2.8 on 2025-11-26 10:53

import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(db_index=True)),
                ('candidate_id', models.UUIDField(db_index=True)),
                ('job_order_id', models.UUIDField(db_index=True, null=True)),
                ('employer_id', models.UUIDField(db_index=True, null=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('margin_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'reports_candidate_report',
                'indexes': [models.Index(fields=['company_id', 'candidate_id'], name='reports_can_company_23fc1c_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobOrderReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(db_index=True)),
                ('job_order_id', models.UUIDField(db_index=True)),
                ('employer_id', models.UUIDField(db_index=True, null=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('avg_margin_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'reports_joborder_report',
                'indexes': [models.Index(fields=['company_id', 'job_order_id'], name='reports_job_company_8212e4_idx')],
            },
        ),
    ]
