# Generated by Django 5.2.8 on 2025-11-25 07:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={},
        ),
        migrations.AlterModelOptions(
            name='billline',
            options={},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={},
        ),
        migrations.AlterModelOptions(
            name='candidate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='candidatecost',
            options={},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='companyprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Currencies'},
        ),
        migrations.AlterModelOptions(
            name='employer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='invoiceline',
            options={},
        ),
        migrations.AlterModelOptions(
            name='joborder',
            options={},
        ),
        migrations.AlterModelOptions(
            name='journal',
            options={},
        ),
        migrations.AlterModelOptions(
            name='journalline',
            options={},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={},
        ),
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='branch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='candidatecost',
            name='reimbursable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='base_currency',
            field=models.CharField(choices=[('INR', 'Indian Rupee'), ('KES', 'Kenyan Shilling'), ('AED', 'UAE Dirham'), ('QAR', 'Qatari Riyal'), ('PHP', 'Philippine Peso'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='AED', max_length=3),
        ),
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='short_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_name',
            field=models.CharField(default='VAT', max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='agreed_fee',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='num_positions',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='account',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wip_account', models.CharField(default='1200 - Work in Progress', max_length=100)),
                ('accounts_receivable', models.CharField(default='1100 - Accounts Receivable', max_length=100)),
                ('accounts_payable', models.CharField(default='2100 - Accounts Payable', max_length=100)),
                ('tax_payable', models.CharField(default='2200 - VAT/GST Payable', max_length=100)),
                ('revenue_account', models.CharField(default='4000 - Placement Revenue', max_length=100)),
                ('cogs_account', models.CharField(default='5000 - Cost of Services', max_length=100)),
                ('fx_gain', models.CharField(default='8100 - Foreign Exchange Gain', max_length=100)),
                ('fx_loss', models.CharField(default='9100 - Foreign Exchange Loss', max_length=100)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chart_of_accounts', to='core.company')),
            ],
            options={
                'db_table': 'chart_of_accounts',
            },
        ),
        migrations.CreateModel(
            name='EmployerContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('renewal_option', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTO', 'Auto-Renew'), ('NONE', 'Do Not Renew')], default='MANUAL', max_length=10)),
                ('renewal_count', models.IntegerField(default=0)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('notes', models.TextField(blank=True)),
                ('notify_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='core.employer')),
            ],
            options={
                'db_table': 'employer_contracts',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(choices=[('USD', 'USD'), ('AED', 'AED'), ('QAR', 'QAR'), ('INR', 'INR'), ('KES', 'KES'), ('PHP', 'PHP'), ('EUR', 'EUR')], max_length=3)),
                ('to_currency', models.CharField(choices=[('USD', 'USD'), ('AED', 'AED'), ('QAR', 'QAR'), ('INR', 'INR'), ('KES', 'KES'), ('PHP', 'PHP'), ('EUR', 'EUR')], max_length=3)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('rate_date', models.DateField(db_index=True)),
                ('source', models.CharField(blank=True, default='Manual', max_length=50)),
            ],
            options={
                'verbose_name': 'FX Rate',
                'verbose_name_plural': 'FX Rates',
                'db_table': 'fx_rates',
                'ordering': ['-rate_date'],
                'unique_together': {('from_currency', 'to_currency', 'rate_date')},
            },
        ),
    ]
